### ISSUE TITLE
Tracking issue: Open-sourcing LighthouseFlux.jl

### ISSUE THREAD

**Issue by hannahilea** [beacon-biosignals/LighthouseFlux.jl#14]
As part of the Julia industry Contributhon, we're going to open source Lighthouse.jl and LighthouseFlux.jl. Hooray! Here's what needs to happen. 

Task list
- [x] Make this tracking issue :) 
- [x] [Open source Lighthouse.jl](https://github.com/beacon-biosignals/Lighthouse.jl) - [tracking issue](https://github.com/beacon-biosignals/OldLighthouse.jl/issues/136)
  - [x] Bump Lighthouse dependency
- [x] Determine whether we need to follow [clean vs generic](https://github.com/beacon-biosignals/knowledge-base/blob/6ccb46c5cdeda2ef5825ad771a6cf75cc0a10f29/engineering-handbook/development-practices.md#open-source-code-vs-closed-source-code) upgrade path, and update this task list accordingly  ---> Can make current repo public
  - [x] Sanity-check no private info in commits/issues (w/ @jrevels)
  - [x] No private info in code 
- [x] Pre-make public commit:
  - [x] Add MIT license
  - [x] Make sure repo follows best-practice settings
  - [x] Make docs build
    - [x] Make sure docs are relatively up to date
  - [x] Add docs badges to readme
  - [x] Add tagbot github action
  - [x] Bump minor version
  - [x] Fix failing test for Lighthouse v0.10.0 - https://github.com/beacon-biosignals/LighthouseFlux.jl/pull/17
- [x] Lint it - https://github.com/beacon-biosignals/LighthouseFlux.jl/pull/16
- [x] Make repo public
- [x] Have @jrevels enable repo access for the general julia registrator
- [x] Open PR in Julia registry - https://github.com/JuliaRegistries/General/pull/26116
  - [x] Wait for it to auto-merge
